FROM node:16-alpine

# ENV NODE_VERSION 16.17.1

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json ./
COPY package-lock.json ./

# Run npm install
# RUN npm install

# Bundle app source
COPY . .

EXPOSE 5000
# CMD ["npm", "run", "start"]
CMD [ "nodemon" ]